name: Build README -> Static Page & Deploy to Vercel

on:
  push:
    branches: [main, man]
    paths:
      - README.md
      - .github/workflows/deploy-vercel.yml
      - vercel.json

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Converte README.md -> dist/index.html
      - name: Build static HTML from README.md
        run: |
          mkdir -p dist
          npm i -g marked@12
          cat > dist/_prefix.html <<'HTML'
          <!doctype html>
          <html lang="pt-br">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <title>README</title>
            <style>
              body { max-width: 900px; margin: 40px auto; padding: 0 16px; font-family: system-ui, sans-serif; line-height: 1.6; }
              pre, code { font-family: monospace; }
              img { max-width: 100%; height: auto; }
            </style>
          </head>
          <body>
          HTML

          cat > dist/_suffix.html <<'HTML'
          </body>
          </html>
          HTML

          marked README.md > dist/_content.html
          cat dist/_prefix.html dist/_content.html dist/_suffix.html > dist/index.html
          rm dist/_prefix.html dist/_content.html dist/_suffix.html

      - name: Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm i -g vercel@latest
          vercel pull --yes --environment=production \
            --token "$VERCEL_TOKEN" \
            --project-id "$VERCEL_PROJECT_ID"

          vercel deploy --prod --yes \
            --token "$VERCEL_TOKEN" \
            --cwd ./dist
